version: '3.8'
services:
    gateway:
       build: shele-microservice-app/SpringApiGetaway
       ports:
         - 8443:8445
       environment:
         ##-SPRING_PROFILES_ACTIVE=docker
        ## -SERVER_SSL_KEY_STORE=file:/keystore/shele.p12
         ##-SERVER_SSL_KEY_STORE_PASSWORD=password
         - SPRING_REDIS_HOST=redis_cache
       volumes:
         - $PWD/keystore:/keystore

       restart: on-failure

    redis_cache:
     image: "redis:7.0"
     restart: on-failure
     command: [ "redis-server","--bind","redis_cache","--port","6379" ]
     ports:
      - "6379:6379"
