version: '3.8'
services:
    gateway:
       build: SpringApiGetaway
       ports:
         - 8443:8445
       environment:
         ##-SPRING_PROFILES_ACTIVE=docker
        ## -SERVER_SSL_KEY_STORE=file:/keystore/shele.p12
         ##-SERVER_SSL_KEY_STORE_PASSWORD=password
         - SPRING_REDIS_HOST=redis_cache
       volumes:
         - $PWD/keystore:/keystore

       restart: on-failure

