server.port=8013
spring.application.name=recommendation-ws
spring.data.mongodb.database=${DB_NAME:recommendation_db}
spring.data.mongodb.host=${HOST:localhost}
spring.data.mongodb.port=${DB_PORT:27017}

logging.level.root=debug

eureka.client.enabled=${EUREKA_ENABLED:false}
eureka.client.service-url.defaultZone=http://localhost:8010/eureka
spring.devtools.restart.enabled=true
eureka.instance.prefer-ip-address=true
